version: '3.8'

services:
  frontend:
    # Nombre para identificarlo fácil en Docker Desktop
    container_name: mi-frontend-container
    
    # Construye la imagen usando el Dockerfile de la carpeta actual
    build: .
    
    # Mapeo de puertos: "PuertoPC : PuertoContenedor"
    ports:
      - "5173:80"
    
    # Variables de entorno
    environment:
      - VITE_API_URL=http://127.0.0.1:8000/api
    
    # Si se cae por error, intenta reiniciarlo automáticamente
    restart: always